force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>Custom Object to store information about countries.</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Country__c/fields/alpha2code__c.field-meta.xml
<CustomField>
    <fullName>alpha2code__c</fullName>
    <description>2 characters country ISO code as described in the ISO 3166 international standard.</description>
    <externalId>true</externalId>
    <label>Alpha-2 Code</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Country__c/fields/alpha3code__c.field-meta.xml
<CustomField>
    <fullName>alpha3code__c</fullName>
    <description>3 characters country ISO code as described in the ISO 3166 international standard.</description>
    <externalId>true</externalId>
    <label>Alpha-3 Code</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Country__c/fields/CapitalCity__c.field-meta.xml
<CustomField>
    <fullName>CapitalCity__c</fullName>
    <label>Capital city</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/FlagImageUrl__c.field-meta.xml
<CustomField>
    <fullName>FlagImageUrl__c</fullName>
    <label>Flag Image URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/RegionalBlocs__c.field-meta.xml
<CustomField>
    <fullName>RegionalBlocs__c</fullName>
    <label>Regional Blocs</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CountryInfo__c.field-meta.xml
<CustomField>
    <fullName>CountryInfo__c</fullName>
    <label>Country Info</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/CountryTriggerHelper.cls
public class CountryTriggerHelper {
    public static void updateRelatedLeads(Map<Id,Country__c> triggerNewMap,Map<Id,Country__c> triggerOldMap){
        Map<String,String> modifiedCountriesSummaries = new Map<String,String>();
        
        // Loop through the triggerNewMap to find modified countries
        for (Country__c newCountry : triggerNewMap.values()) {
            Country__c oldCountry = triggerOldMap?.get(newCountry.Id);
            
            if (oldCountry == null || countryHasChanged(oldCountry, newCountry)) {
                modifiedCountriesSummaries.put(newCountry.Alpha2Code__c, getCountrySummary(newCountry));
            }
        }
        
        // If there are modified countries, update related leads
        if (!modifiedCountriesSummaries.isEmpty()) {
            List<Lead> leadsToUpdate = new List<Lead>();
            
            for (Lead lead : [SELECT Id, CountryCode, CountryInfo__c FROM Lead WHERE CountryCode IN :modifiedCountriesSummaries.keySet()]) {
                lead.CountryInfo__c = modifiedCountriesSummaries.get(lead.CountryCode);
                leadsToUpdate.add(lead);
            }

            if (!leadsToUpdate.isEmpty()) {
                update leadsToUpdate;
            }
        }
    }

    //Checks if country has changed
    private static boolean countryHasChanged(Country__c oldCountry, Country__c newCountry){
        return !(oldCountry.Name == newCountry.Name
                 && oldCountry.Alpha2Code__c == newCountry.Alpha2Code__c
                 && oldCountry.Alpha3Code__c == newCountry.Alpha3Code__c
                 && (oldCountry.CapitalCity__c == newCountry.CapitalCity__c || (String.isBlank(oldCountry.CapitalCity__c) && String.isBlank(newCountry.CapitalCity__c)))
                 && oldCountry.FlagImageUrl__c == newCountry.FlagImageUrl__c
                 && (oldCountry.Region__c == newCountry.Region__c || (String.isBlank(oldCountry.CapitalCity__c) && String.isBlank(newCountry.CapitalCity__c)))
                 && oldCountry.RegionalBlocs__c == newCountry.RegionalBlocs__c);
    }

    //Returns formatted country information summary
    public static String getCountrySummary(Country__c country) {
        if (country == null) return '';
        
        String summary = 'Country: ' + country.Name + '\n';
        
        if (String.isNotBlank(country.CapitalCity__c)) {
            summary += 'Capital: ' + country.CapitalCity__c + '\n';
        }
        
        if (String.isNotBlank(country.Region__c)) {
            summary += 'Region: ' + country.Region__c + '\n';
        }
        
        if (String.isNotBlank(country.Alpha2Code__c)) {
            summary += 'Country Codes: ' + country.Alpha2Code__c + '/' + country.Alpha3Code__c + '\n';
        }
        
        if (String.isNotBlank(country.RegionalBlocs__c)) {
            summary += 'Regional Blocs: ' + country.RegionalBlocs__c + '\n';
        }
        
        return summary;
    }
}