force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>Custom Object to store information about countries.</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Country__c/fields/alpha2code__c.field-meta.xml
<CustomField>
    <fullName>alpha2code__c</fullName>
    <description>2 characters country ISO code as described in the ISO 3166 international standard.</description>
    <externalId>true</externalId>
    <label>Alpha-2 Code</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Country__c/fields/alpha3code__c.field-meta.xml
<CustomField>
    <fullName>alpha3code__c</fullName>
    <description>3 characters country ISO code as described in the ISO 3166 international standard.</description>
    <externalId>true</externalId>
    <label>Alpha-3 Code</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Country__c/fields/CapitalCity__c.field-meta.xml
<CustomField>
    <fullName>CapitalCity__c</fullName>
    <label>Capital city</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CountriesUpdate_SchedulableTest.cls
@isTest
public class CountriesUpdate_SchedulableTest {

    @TestSetup
    static void setup() {
        Country__c afghanistan = new Country__c(
            Name = 'Afghanistan',
            CapitalCity__c = 'NotKabul',
            Alpha2Code__c = 'AF',
            Alpha3Code__c = 'AFG'
        );
        insert afghanistan;
        
        List<Lead> leads = new List<Lead>{
            new Lead(LastName = 'Test1', Company = 'Test1 Corp', Country = 'Afghanistan'),
            new Lead(LastName = 'Test2', Company = 'Test2 Corp', Country = 'Afghanistan')
        };
        insert leads;
    }

@IsTest
    private static void testExecute(){
        Test.setMock(HttpCalloutMock.class, new CountryLayerAPI_Mock());

        Test.startTest();
        CountriesUpdate_Schedulable schedulable = new CountriesUpdate_Schedulable();
        schedulable.execute(null);
        Test.stopTest();

        List<Country__c> countries = [SELECT Id FROM Country__c];
        System.assertEquals(2, countries.size());
    }
    
    @IsTest
    private static void testExecuteWithException(){
        
        Test.startTest();
        CountriesUpdate_Schedulable schedulable = new CountriesUpdate_Schedulable();
        try {
            schedulable.execute(null);
            System.assert(false, 'Expected exception was not thrown');
        } catch (CountryLayer_Exception e) {
            System.assertEquals('CountryLayer_Connector failed.', e.getMessage());
        }
        Test.stopTest();
    }

}