force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>Custom Object to store information about countries.</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Country__c/fields/alpha2code__c.field-meta.xml
<CustomField>
    <fullName>alpha2code__c</fullName>
    <description>2 characters country ISO code as described in the ISO 3166 international standard.</description>
    <externalId>true</externalId>
    <label>Alpha-2 Code</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Country__c/fields/alpha3code__c.field-meta.xml
<CustomField>
    <fullName>alpha3code__c</fullName>
    <description>3 characters country ISO code as described in the ISO 3166 international standard.</description>
    <externalId>true</externalId>
    <label>Alpha-3 Code</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Country__c/fields/CapitalCity__c.field-meta.xml
<CustomField>
    <fullName>CapitalCity__c</fullName>
    <label>Capital city</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/FlagImageUrl__c.field-meta.xml
<CustomField>
    <fullName>FlagImageUrl__c</fullName>
    <label>Flag Image URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/RegionalBlocs__c.field-meta.xml
<CustomField>
    <fullName>RegionalBlocs__c</fullName>
    <label>Regional Blocs</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/CountriesUpdate_Schedulable.cls
global class CountriesUpdate_Schedulable implements Schedulable {
    global void execute(SchedulableContext sc) {
        Map<String,CountryLayerAPI_Wrapper.CountryWrapper> countriesMap;
        List<Country__c> countriesToUpsert = new List<Country__c>();
        
        try{
            countriesMap = CountryLayer_Connector.getAllCountries();
        } catch (Exception e){
            //Here we should log the Exception into a logging framework.
            System.debug(e);
            throw new CountryLayer_Exception('CountryLayer_Connector failed.', e);
        }
        
        //Check if existing countries have changed
        for(Country__c country : [SELECT Id, Name, Alpha2Code__c, Alpha3Code__c, CapitalCity__c, FlagImageUrl__c, Region__c, RegionalBlocs__c FROM Country__c WHERE Alpha2Code__c IN :countriesMap.keySet()]){
            if(countryHasChanged(country,countriesMap.get(country.Alpha2Code__c))){
                countriesToUpsert.add(convertToCountry(countriesMap.get(country.Alpha2Code__c)));
            }
            
            countriesMap.remove(country.Alpha2Code__c);
        }
        
        //Add all new countries
        for(CountryLayerAPI_Wrapper.CountryWrapper newCountry : countriesMap.values()){
            countriesToUpsert.add(convertToCountry(newCountry));
        }
        
        upsert countriesToUpsert Alpha2Code__c;
    }
    
    private static Country__c convertToCountry(CountryLayerAPI_Wrapper.CountryWrapper countryWrapper){
        Country__c countryToReturn = new Country__c();
        
        countryToReturn.Name = countryWrapper.name;
        countryToReturn.Alpha2Code__c = countryWrapper.alpha2Code;
        countryToReturn.Alpha3Code__c = countryWrapper.alpha3Code;
        countryToReturn.CapitalCity__c = countryWrapper.capital;
        countryToReturn.FlagImageUrl__c = countryWrapper.flag;
        countryToReturn.Region__c = countryWrapper.region;
        countryToReturn.RegionalBlocs__c = countryWrapper.regionalBlocsSummary;
        
        return countryToReturn;
    }
    
    private static boolean countryHasChanged(Country__c country, CountryLayerAPI_Wrapper.CountryWrapper countryWrapper){
        return !(country.Name == countryWrapper.name
                 && country.Alpha2Code__c == countryWrapper.alpha2Code
                 && country.Alpha3Code__c == countryWrapper.alpha3Code
                 && (country.CapitalCity__c == countryWrapper.capital || (String.isBlank(country.CapitalCity__c) && String.isBlank(countryWrapper.capital)))
                 && country.FlagImageUrl__c == countryWrapper.flag
                 && (country.Region__c == countryWrapper.region || (String.isBlank(country.CapitalCity__c) && String.isBlank(countryWrapper.capital)))
                 && country.RegionalBlocs__c == countryWrapper.regionalBlocsSummary);
    }
}